// Generated by gencpp from file test_tools/IMUPacket.msg
// DO NOT EDIT!


#ifndef TEST_TOOLS_MESSAGE_IMUPACKET_H
#define TEST_TOOLS_MESSAGE_IMUPACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace test_tools
{
template <class ContainerAllocator>
struct IMUPacket_
{
  typedef IMUPacket_<ContainerAllocator> Type;

  IMUPacket_()
    : header()
    , wx(0)
    , wy(0)
    , wz(0)
    , ax(0)
    , ay(0)
    , az(0)
    , wheel(0)  {
    }
  IMUPacket_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wx(0)
    , wy(0)
    , wz(0)
    , ax(0)
    , ay(0)
    , az(0)
    , wheel(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _wx_type;
  _wx_type wx;

   typedef int16_t _wy_type;
  _wy_type wy;

   typedef int16_t _wz_type;
  _wz_type wz;

   typedef int16_t _ax_type;
  _ax_type ax;

   typedef int16_t _ay_type;
  _ay_type ay;

   typedef int16_t _az_type;
  _az_type az;

   typedef int16_t _wheel_type;
  _wheel_type wheel;





  typedef boost::shared_ptr< ::test_tools::IMUPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_tools::IMUPacket_<ContainerAllocator> const> ConstPtr;

}; // struct IMUPacket_

typedef ::test_tools::IMUPacket_<std::allocator<void> > IMUPacket;

typedef boost::shared_ptr< ::test_tools::IMUPacket > IMUPacketPtr;
typedef boost::shared_ptr< ::test_tools::IMUPacket const> IMUPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_tools::IMUPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_tools::IMUPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_tools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'test_tools': ['/home/kuriatsu/Program/Ros/mad_mobile_ws/src/test_tools/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_tools::IMUPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_tools::IMUPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_tools::IMUPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_tools::IMUPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_tools::IMUPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_tools::IMUPacket_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_tools::IMUPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d4a54def277a6afd729e1ac2194dc07";
  }

  static const char* value(const ::test_tools::IMUPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d4a54def277a6afULL;
  static const uint64_t static_value2 = 0xd729e1ac2194dc07ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_tools::IMUPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_tools/IMUPacket";
  }

  static const char* value(const ::test_tools::IMUPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_tools::IMUPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 wx\n\
int16 wy\n\
int16 wz\n\
int16 ax\n\
int16 ay\n\
int16 az\n\
int16 wheel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::test_tools::IMUPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_tools::IMUPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wx);
      stream.next(m.wy);
      stream.next(m.wz);
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.az);
      stream.next(m.wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMUPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_tools::IMUPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_tools::IMUPacket_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wx);
    s << indent << "wy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wy);
    s << indent << "wz: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wz);
    s << indent << "ax: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ay);
    s << indent << "az: ";
    Printer<int16_t>::stream(s, indent + "  ", v.az);
    s << indent << "wheel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_TOOLS_MESSAGE_IMUPACKET_H
